### ISSUE TITLE
ValueError: load a weight file containing 40 layers into a model with 53 layers.

### ISSUE THREAD

**Issue by malnakli** [foamliu/Look-Into-Person#1]
Thank you for your work.

when I try to run `demo.py` with the pre-trained model i get the following error

```
Traceback (most recent call last):
  File "demo.py", line 19, in <module>
    model.load_weights(model_weights_path)
  File "/home/beastai/miniconda3/envs/gen-design/lib/python3.6/site-packages/keras/engine/topology.py", line 2656, in load_weights
    f, self.layers, reshape=reshape)
  File "/home/beastai/miniconda3/envs/gen-design/lib/python3.6/site-packages/keras/engine/topology.py", line 3354, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 40 layers into a model with 53 layers.
```

**Comment by visonpon** [comment]
I've also countered this error, it seems the provided model not the test model @foamliu 
Hope you can upload the right pretrained model,thanks~

**Comment by visonpon** [comment]
I've also encountered this error, it seems the model provided not the exacted model used for test.
Hope you can upload the right model @foamliu ,thanks~

**Comment by foamliu** [comment]
Fixed, please have another try.
